### ISSUE TITLE
"Config" has no attribute "get_env_config"

### ISSUE THREAD

**Issue by dividebysandwich** [mov-cli/mov-cli-jellyplex#2]
Hi, I'm getting this error on current arch and python 3.12 when trying to connect to Jellyfin 10.9.3:

```
❯ mov-cli -s ms Mars -- --url "http://192.168.178.11:8096" --username "someusername" --password "somepassword"

Good Evening, user.
    It's 07:52 PM on a gorgeous Thursday!

[INFO] (mov_cli) - Using 'ms.DEFAULT' scraper...
[CRITICAL] (mov_cli) - An error occurred inside a plugin. This is MOST LIKELY not a mov-cli error, make SURE mov-cli and your plugins are up to date. Also report this to the plugin, not mov-cli!
Error: 'Config' object has no attribute 'get_env_config'
Traceback (most recent call last):
  File "/home/user/.local/bin/mov-cli", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/mov_cli/cli/__main__.py", line 154, in app
    uwu_app()
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/typer/main.py", line 326, in __call__
    raise e
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/typer/main.py", line 309, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/typer/core.py", line 661, in main
    return _main(
           ^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/typer/core.py", line 193, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/typer/main.py", line 692, in wrapper
    return callback(**use_params)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/mov_cli/cli/__main__.py", line 96, in mov_cli
    chosen_scraper = use_scraper(selected_scraper, config, http_client, scrape_options)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/mov_cli/cli/scraper.py", line 46, in use_scraper
    handle_internal_plugin_error(e)
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/mov_cli/cli/plugins.py", line 48, in handle_internal_plugin_error
    raise e
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/mov_cli/cli/scraper.py", line 44, in use_scraper
    chosen_scraper = scraper_class(config, http_client, scraper_options)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/mov_cli_ms/jellyfin/scraper.py", line 22, in __init__
    env_config = config.get_env_config()
                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Config' object has no attribute 'get_env_config'
```

**Comment by ananasmoe** [comment]
> Hi, I'm getting this error on current arch and python 3.12 when trying to connect to Jellyfin 10.9.3:
> 
> ```
> ❯ mov-cli -s ms Mars -- --url "http://192.168.178.11:8096" --username "someusername" --password "somepassword"
> 
> Good Evening, user.
>     It's 07:52 PM on a gorgeous Thursday!
> 
> [INFO] (mov_cli) - Using 'ms.DEFAULT' scraper...
> [CRITICAL] (mov_cli) - An error occurred inside a plugin. This is MOST LIKELY not a mov-cli error, make SURE mov-cli and your plugins are up to date. Also report this to the plugin, not mov-cli!
> Error: 'Config' object has no attribute 'get_env_config'
> Traceback (most recent call last):
>   File "/home/user/.local/bin/mov-cli", line 8, in <module>
>     sys.exit(app())
>              ^^^^^
>   File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/mov_cli/cli/__main__.py", line 154, in app
>     uwu_app()
>   File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/typer/main.py", line 326, in __call__
>     raise e
>   File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/typer/main.py", line 309, in __call__
>     return get_command(self)(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/typer/core.py", line 661, in main
>     return _main(
>            ^^^^^^
>   File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/typer/core.py", line 193, in _main
>     rv = self.invoke(ctx)
>          ^^^^^^^^^^^^^^^^
>   File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/typer/main.py", line 692, in wrapper
>     return callback(**use_params)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/mov_cli/cli/__main__.py", line 96, in mov_cli
>     chosen_scraper = use_scraper(selected_scraper, config, http_client, scrape_options)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/mov_cli/cli/scraper.py", line 46, in use_scraper
>     handle_internal_plugin_error(e)
>   File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/mov_cli/cli/plugins.py", line 48, in handle_internal_plugin_error
>     raise e
>   File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/mov_cli/cli/scraper.py", line 44, in use_scraper
>     chosen_scraper = scraper_class(config, http_client, scraper_options)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/mov_cli_ms/jellyfin/scraper.py", line 22, in __init__
>     env_config = config.get_env_config()
>                  ^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'Config' object has no attribute 'get_env_config'
> ```

What command did you use for the installation of mov-cli-media-server?

For the git version of mov-cli-media-server, you have to use mov-cli v4.4a4 but NOTE it maybe buggy.

```sh
pipx install mov-cli==4.4a4
```

**Comment by dividebysandwich** [comment]
I used:

```
pipx install mov-cli --include-deps
pipx inject mov-cli mov-cli-ms
```

When I try to use 4.4a4 as you suggested, I get a different error:

```
[CRITICAL] (mov_cli) - An error occurred inside a plugin. This is MOST LIKELY not a mov-cli error, make SURE mov-cli and your plugins are up to date. Also report this to the plugin, not mov-cli! 
Error: Request URL is missing an 'http://' or 'https://' protocol.
Traceback (most recent call last):
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 167, in handle_request
    raise UnsupportedProtocol(
httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
```

The youtube plugin works in both cases.

**Comment by ananasmoe** [comment]
> I used:
> 
> ```
> pipx install mov-cli --include-deps
> pipx inject mov-cli mov-cli-ms
> ```
> 
> When I try to use 4.4a4 as you suggested, I get a different error:
> 
> ```
> [CRITICAL] (mov_cli) - An error occurred inside a plugin. This is MOST LIKELY not a mov-cli error, make SURE mov-cli and your plugins are up to date. Also report this to the plugin, not mov-cli! 
> Error: Request URL is missing an 'http://' or 'https://' protocol.
> Traceback (most recent call last):
>   File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
>     yield
>   File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/httpx/_transports/default.py", line 233, in handle_request
>     resp = self._pool.handle_request(req)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 167, in handle_request
>     raise UnsupportedProtocol(
> httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
> ```
> 
> The youtube plugin works in both cases.

I forgot to mention in v4.4a4, you will need to use envs. See this wiki page on how to use them: https://github.com/mov-cli/mov-cli/wiki/Configuration#environment-variables

ENVs that should be set are:
`JELLY_URL`
`JELLY_USERNAME`
`JELLY_PASSWORD`

after that you can use mov-cli-ms like this:
`mov-cli -s ms Mars`

**Comment by dividebysandwich** [comment]
Thanks! Unfortunately, yet another error. This time whenever there's one or more search hits, I get this:

```
❯ mov-cli -s ms Mars

Good Afternoon, user.
    It's 03:19 PM on a wonderful Saturday! 

[INFO] (mov_cli) - Using 'ms.DEFAULT' scraper...
[INFO] (mov_cli) - Searching for 'Mars'...
Traceback (most recent call last):
  File "/home/user/.local/bin/mov-cli", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/mov_cli/cli/__main__.py", line 147, in app
    uwu_app()
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/typer/main.py", line 326, in __call__
    raise e
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/typer/main.py", line 309, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/typer/core.py", line 661, in main
    return _main(
           ^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/typer/core.py", line 193, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/typer/main.py", line 692, in wrapper
    return callback(**use_params)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/mov_cli/cli/__main__.py", line 104, in mov_cli
    choice = search(query, auto_select, chosen_scraper, config.fzf_enabled, limit)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/mov_cli/cli/search.py", line 31, in search
    choice = prompt(
             ^^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/mov_cli/cli/ui.py", line 76, in prompt
    is_just_one, choices = is_it_just_one_choice(choices)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/mov_cli/cli/ui.py", line 56, in is_it_just_one_choice
    for index, _ in enumerate(choices):
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/mov_cli/cli/search.py", line 33, in <genexpr>
    choices = (choice for choice in search_results), 
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/mov-cli/lib/python3.12/site-packages/mov_cli_ms/jellyfin/scraper.py", line 74, in search
    type = MetadataType.MOVIE if item["Type"] == "Movie" else MetadataType.SERIES,
           ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'MetadataType' has no attribute 'MOVIE'
```

When there's no match, I get the normal "There was no results" 

EDIT: It seems MetadataType.MOVIE has been deprecated in favor of .SINGLE

**Comment by ananasmoe** [comment]
Install the alpha version of mov-cli-media-server: `pipx inject mov-cli mov-cli-ms==1.1.0a1`

**Comment by dividebysandwich** [comment]
That worked, thanks!
